version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - my-network
    command: ["--log-bin-trust-function-creators=1"]
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uuser -ppassword || exit 1"]
      interval: 10s
      retries: 5

  flyway:
    image: flyway/flyway:8.0.0
    container_name: flyway_migration
    depends_on:
      mysql_db:
        condition: service_healthy   # Wait until MySQL is healthy
    entrypoint: ["flyway", "migrate"]
    environment:
      FLYWAY_URL: jdbc:mysql://mysql_db:3306/mydb
      FLYWAY_USER: user
      FLYWAY_PASSWORD: password
    volumes:
      - ./flyway/sql:/flyway/sql
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
