CREATE TABLE IF NOT EXISTS player_data (
    id INT AUTO_INCREMENT PRIMARY KEY,
    fpl_id INT,
    fpl_code INT,
    team_id INT,
    first_name VARCHAR(50),
    second_name VARCHAR(50),
    chance_of_playing FLOAT,
    form FLOAT,
    total_points INT,
    goals INT,
    assists INT,
    clean_sheets INT,
    goals_conceeded INT,
    penalties_saved INT,
    penalties_missed INT,
    yellow_cards INT,
    red_cards INT,
    saves INT,
    bonus_points INT,
    starts INT,
    expected_goals FLOAT,
    expected_assists FLOAT,
    expected_goals_conceeded FLOAT,
    expected_goal_involvments FLOAT,
    FOREIGN KEY (team_id) REFERENCES team_data(id)
);